### ISSUE TITLE
Lighter (disabled?) text drawn for unfocused views.

### ISSUE THREAD

**Issue by CDrummond** [FedoraQt/adwaita-qt#126] opened 2019-12-04 10:49 UTC
As can be seen in the following kid3-qt screenshot, a ligher grey text is used to draw views that currently don't have focus. This looks odd, and (espcially in kd3-qt's case) makes the app harder to use.

![kid3-text](https://user-images.githubusercontent.com/1141694/70136253-8ff5d100-1683-11ea-8301-ca33fef93041.png)

The vie won th eleft also does not have focus, so not sure exactly what is going on. But, if the table-view within the right had side vide gets focus, then its text turns black.

**Comment by grulja** [comment] 2020-04-20 16:08
I pushed https://github.com/FedoraQt/adwaita-qt/commit/e671e8e88d90332d65e3f8396bb98393fc50bafe, which fixes it for QTreeView, but I was unable to find a solution for QTableView and QListView. They seem to be rendered differently and I already spent hours trying to find a solution. I will keep this opened, but I have no idea at this moment how to fix it.

**Comment by uklotzde** [comment] 2020-05-15 11:59
Mixxx also seems to be affected by the latest changes in 1.1.2 (crashes) and 1.1.3. Both QTreeView and QTableView are affected depending on focus:

adwaita-qt5-1.1.1:
![palette_before](https://user-images.githubusercontent.com/1474154/82047896-e6941c00-96b3-11ea-851b-c526271ab6aa.png)

adwaita-qt5-1.1.3:
![palette_after](https://user-images.githubusercontent.com/1474154/82047919-f0b61a80-96b3-11ea-9239-e84c16736d6c.png)

Version 1.1.1 worked for us, version 1.1.2/1.1.3 is unusable right now.

**Comment by uklotzde** [comment] 2020-05-15 12:09
Colors in QTreeView and QTableViw are now changing from inactive to active in unforeseeable ways depending on the focus. Maybe caused by the recent commits during Apr 2020 targeting unfocused views?

**Comment by grulja** [comment] 2020-05-15 12:32
The reason why I did it this way is that Qt doesn't distinguish between inactive widget and inactive window. For example you could have a tree view in your app, the app had focus on a different widget and the tree view was grey, looking like the whole application not having focus. To fix that, I just check whether the main window has focus and set inactive palette to have colors from the active one. 

Why Mixxx use grey color for text when it's active?

**Comment by uklotzde** [comment] 2020-05-15 12:44
The screenshots were taken with Mixxx in fullscreen mode. I need to check whether switching the window modes affects the behavior.

Maybe @ronso0 could provide some insights how the focus handling between different views in Mixxx works.

**Comment by grulja** [comment] 2020-05-15 13:18
Ok, I think I know why this is happening. You probably set some custom color to the view and we change it back to Adwaita default palette when the window looses focus. I will fix it during the weekend.

**Comment by grulja** [comment] 2020-05-18 10:56
Can you try https://github.com/FedoraQt/adwaita-qt/commit/e5dfd0be75b31dc3b823de0c4bd320b9a6995b89 for the Mixxx issue?

**Comment by uklotzde** [comment] 2020-05-18 11:59
Great! Works as expected in all modes (fullscreen/window). The color scheme is now preserved after activating the menu bar.

@Be-ing @ronso0 Tested with both Deere and Tango on master.

**Comment by Be-ing** [comment] 2020-05-18 12:45
That works, but I can only get the theme to apply to Qt applications when I run them from KDE... now my fonts are all tiny after changing something in KDE system settings... even erasing ~/.config didn't fix it :cry:

**Comment by grulja** [comment] 2020-05-18 12:53
> That works, but I can only get the theme to apply to Qt applications when I run them from KDE... now my fonts are all tiny after changing something in KDE system settings... even erasing ~/.config didn't fix it

You can force the theme with QT_STYLE_OVERRIDE=adwaita.

No idea why your fonts are tiny, this is unfortunately not related to Adwaita at all.

**Comment by Awem** [comment] 2020-07-02 17:35
On adwaita-qt 1.1.4 KeePassXC still looks like this:
![image](https://user-images.githubusercontent.com/4180877/86392051-18306900-bc9b-11ea-910d-ae6574217c1c.png)
Is there some way to fix this?

**Comment by grulja** [comment] 2020-07-06 17:22
> On adwaita-qt 1.1.4 KeePassXC still looks like this:
> ![image](https://user-images.githubusercontent.com/4180877/86392051-18306900-bc9b-11ea-910d-ae6574217c1c.png)
> Is there some way to fix this?
> 
> This is how it looks on 1.1.1:
> ![image](https://user-images.githubusercontent.com/4180877/86518011-03d0a580-be2e-11ea-9fc8-dcfe4de87ac7.png)

Can you be more specific about the area where you see this? Maybe a whole screenshot? Running it myself I don't have any problem with it.

**Comment by Awem** [comment] 2020-07-06 17:59
Ah, okay. Maybe this helps:

1. create a new entry with any title
2. choose "clone entry" on the context menu of that new entry
3. make sure the second checkbox concerning the references is checked

**Comment by Awem** [comment] 2020-07-14 10:50
@grulja the light text is no longer an issue with KeePassXC 2.6.0

**Comment by polter-rnd** [comment] 2022-12-01 07:49
Fixed in https://github.com/FedoraQt/adwaita-qt/pull/183

**Closed** 2022-12-07 07:47 UTC
Labels: bug, help wanted
