### ISSUE TITLE
Can't set Adwaita-dark

### ISSUE THREAD

**Issue by dawidpotocki** [FedoraQt/adwaita-qt#140] opened 2020-07-05 12:41 UTC
```sh
export QT_STYLE_OVERRIDE=adwaita-dark
```

I had this line for a long time in my `~/.profile`. Few… uh… weeks(?) ago
it started giving me standard `Adwaita` instead of `-dark`. Adding
`-style Adwaita-Dark` as a flag also doesn't work.

I'm using Void Linux with dwm, but it doesn't work for other people with
different setup on Arch with i3 either.

Qt: 5.15.0
Adwaita-Qt: 1.1.4

**Comment by grulja** [comment] 2020-07-06 17:18
Works for me with Qt 5.14. I don't have a way to easily test Qt 5.15 at this moment, but it doesn't seem to be a bug on our side.

**Comment by n-st** [comment] 2020-07-10 13:54
I encountered the same problem when I upgraded to Qt 5.15.
It affects not only the `QT_STYLE_OVERRIDE` environment variable, but also programs that provide a style selector of their own (e.g. Master PDF Editor): They correctly apply any of the installed themes when I select one of them; only Adwaita-Dark looks exactly like Adwaita.
Maybe there's an incompatibility somewhere?

**Comment by szanni** [comment] 2020-08-30 14:11
Can confirm. Qt 5.15.

The window styles are still applied, e.g. using vlc: the checkboxes do appear a little darker than with the normal adwaita theme applied.
The problem is that the background color **does not** change and stays uncomfortably bright.

**Comment by grulja** [comment] 2020-09-01 05:02
I believe this will be fixed with Qt 5.15.1.

There are some bugs reported for this issue: 
1) https://bugreports.qt.io/browse/QTBUG-85469
2) https://bugreports.qt.io/browse/QTBUG-86362

And fixed with https://github.com/qt/qtbase/commit/7218665699e31ac8eebab17afd684d1a56d12ac3.

**Closed by grulja** 2020-09-01 05:02 UTC
