### ISSUE TITLE
Background color changed (again)

### ISSUE THREAD

**Issue by DDZ57** [FedoraQt/adwaita-qt#95] opened 2017-06-15 09:07 UTC
Hello

It seems the background color isn't #E9E9E9 anymore but now #E8E8E7.
When you wrote "Colors should now be taken from the system." in issue #23, what does it mean ? When does the system store this information?
Because there's still the same problem.

Thank you in advance for your answer and have a nice day!

**Comment by MartinBriza** [comment] 2017-06-15 09:14
The colors are taken from the theme Qt uses by default. This depends on the operating system and the theme in your desktop environment (if there is any).

**Comment by DDZ57** [comment] 2017-06-15 13:49
Do you talk about QT 5 theme?
I use Adwaita (set through qt5ct).

Both QT 4 and KDE 4 use QtCurve with Adwaita like style (with rights colours).

GTK use Adwaita, of course.

**Comment by MartinBriza** [comment] 2017-06-15 15:25
Qt5, yes. In case you use qt5ct you should probably switch to the Custom palette in settings. I think the default is taken from somewhere else and it looks pretty ugly.

**Comment by DDZ57** [comment] 2017-06-15 18:30
Already done. :-)

**Comment by DDZ57** [comment] 2017-06-26 21:40
I updated qt5ct from 0.30 (buggy) to 0.33 version.
-> Same problem! :(

**Comment by MartinBriza** [comment] 2017-06-27 14:33
Well, I'm convinced this is caused by what you have in qt5ct, not the theme itself.

**Comment by DDZ57** [comment] 2017-07-03 07:48
So, can you send me your ~/.config/qt5ct/qt5ct.conf?
Thank you in advance.

**Comment by MartinBriza** [comment] 2017-09-06 10:02
I can't, sorry. I'm not running qt5ct. :(

**Comment by DDZ57** [comment] 2017-10-03 21:15
QT 4 version works fine (with the right #E8E8E7 background color), QT 5 version not.
You aren't running qt5ct, so what does you use to set QT 5 appearance settings?

**Comment by grulja** [comment] 2019-07-02 11:40
Fixed with https://github.com/FedoraQt/adwaita-qt/releases/tag/1.0.90.

**Closed by grulja** 2019-07-02 11:40 UTC
