### ISSUE TITLE
Does not match new Adwaita refresh

### ISSUE THREAD

**Issue by louis-irl** [FedoraQt/adwaita-qt#110] opened 2019-02-04 23:02 UTC
GTK 3.24.5 was just released, which features the new Adwaita refresh.  Adwaita-Qt uses the old style currently.

**Comment by ripefig** [comment] 2019-02-26 20:25
This may be also good opportunity to iron our the rough edges in the current theme as well. Right now, there are ugly borders all over the place, the menu-bar active and inactive states don't match gnome's, scrollbars don't match, colors are not 1:1 etc.

Perhaps it would be easier to do with KVantum now though. I've created a https://github.com/tsujan/Kvantum/issues/347

It would be nice to just able to use just Adwaita on KDE insead of breeze. But the theme would need to be polished for it be used as whole desktop theme.

**Comment by MartinBriza** [comment] 2019-03-01 19:51
@suckybell You're right and I'm aware, I just didn't get around to do it and I'm not sure if that'll happen in the foreseeable future. I'm not alone though, so the other maintainers or even somebody else could step up and help with fixing the theme.

However, it would make our work *MUCH* easier if you guys stepped up and opened issues for each element that looks off, compared to the new Adwaita theme. I created the "Adwaita refresh" milestone. Feel free to assign new issues to it, if they fit the bill.

**Comment by MartinBriza** [comment] 2019-03-01 19:57
@ripefig Sorry man, this is pretty vague. I'm not going to fix "ugly borders all over the place" because I'm not sure what does that mean.

If polish is what you lack in this theme, please feel free to open separate issues for each element that looks off. I'm but a mere developer with eyesight that gets worse each and every day and I'm using Breeze nowadays, I have to admit. I'm not saying I'll start fixing the issues right away but I have a few cycles left here and there so the situation could improve over some time. Oh and it'll also make it easier for other people and other maintainers to step in and fix an issue or two when they have time.

One thing that is sure is I'm not going to do a Kvantum theme simply because I don't know how and starting from the scratch doesn't seem very tempting, sorry.

**Comment by Esokrates** [comment] 2019-05-05 09:09
@MartinBriza I would vote for considering joining efforts with Kvantum, since
1.) Kvantum fixed issues which have been open here for quite some time
2.) Kvantum currently provides a theme matching the new style of Adwaita, see https://github.com/tsujan/Kvantum/issues/347 and the dev promised to update the theme every half a year to match new changes. 
3.) Kvantum is not just great for Adwaita but also for providing a great match for other popular gtk themes, so the goal of the project is a strict superset of this project.
4.) Less duplicated effort, since adwaita-qt has served its purpose well in the past, but now it seems the time has come that the devs don't have enough time to make bigger changes, which also would speak for helping Kvantum with maintaining their Adwaita theme. 
5.) There a few things you could help Kvantum, like getting it into Flatpak, see https://github.com/flatpak/flatpak/issues/2030

**Comment by grulja** [comment] 2019-05-06 13:34
The Kvantum Adwaita theme is, in my opinion, far from being perfect. I tried it and it doesn't really look good. I'm working on a new version of adwaita-qt, trying to match the current Gtk's Adwaita theme. The work is being done in "adwaita-refresh" branch. Feel free to try it if you are interested, but there is still lots of work that needs to be done.

**Comment by Esokrates** [comment] 2019-05-11 19:49
@grulja First of all thanks for testing kvantum and for taking care of the situation. What version kvantum did you test? In older versions the theme was broken, I tested fairly recent versions and it looked almost like a perfect match, the only minor thing I found better in adwaita-qt was the font rendering. So "doesn't really look good" sounds like you observed some problem. 

I just wanted to demonstrate this to you, but your demo application in the refresh branch does not compile: First of all there is a cmake issue with "qt5_wrap_ui" which I was able to fix with `find_package(Qt5 COMPONENTS Widgets REQUIRED)`, but after that compiling failed.

**Comment by grulja** [comment] 2019-05-12 13:45
Can you share the error you get during the build?

I tried latest Kvantum (I compiled current master) and here you can see the results:
1) Adwaita - [https://jgrulich.fedorapeople.org/adwaita.png](url)
2) Kvantum - [https://jgrulich.fedorapeople.org/kvantum.png](url)

**Comment by Esokrates** [comment] 2019-05-12 16:26
My command line log can be found here:
https://pastebin.com/7u1qhp0d
Would be great if you could fix this, I don't have C++/Qt experience.

Regarding your screenshots: The tabs in my version of kvantum looked like the tabs in adwaita-qt, so I guess there is some kind of regression on the side of kvantum then.

**Comment by grulja** [comment] 2019-05-13 06:40
You need to build the demo together with the adwaita style, from the main source directory. Just pass "-DBUILD_EXAMPLE=true" option to cmake command.

**Comment by ripefig** [comment] 2019-05-13 14:58
Is theming the QT CSDs within the scope of this project? That's will be the biggest problem with QT apps on Gnome Wayland - they have horrible stock CSDs.

**Comment by grulja** [comment] 2019-06-25 13:43
Qt window decorations (for Wayland) will be part of [QGnomePlatform](https://github.com/FedoraQt/QGnomePlatform/tree/wayland-decoration). My work on the refreshed adwaita theme can be tested from here https://github.com/FedoraQt/adwaita-qt/pull/111. Feel free to test and comment.

**Comment by ripefig** [comment] 2019-06-25 20:49
Great. Can you ensure that the window can be dragged from anywhere in the titlebar, not just empty space? 

One of the biggest problems with CSD is that the de facto Gnome standard allows dragging from widget areas but nobody else implements this feature. As a result, the simple act of dragging windows becomes wildly inconsistent. Right now, you literally have to stop and think whether the CSD app you're using is GTK or not before dragging a window, which is just horrendous UX.

**Comment by ripefig** [comment] 2019-06-25 20:56
One other thing is that the QT apps tend to have borders around widget areas that aren't flush with the window decoration. That's one of the main visual inconsistencies between QT and GTK.

![image](https://user-images.githubusercontent.com/45201036/60132556-64052400-97a4-11e9-9c5b-f43582d55a74.png)

This is an example from the Dolphin app - there are just borders all over the place. Is it technically feasible to to have the widget area border - if it exists - be flush with the window decoration?

**Comment by grulja** [comment] 2019-07-02 11:38
Can be closed now, new adwaita version has been released. If there is still anything wrong, and there certainly is, please open new bugs for particular issues.

See: https://github.com/FedoraQt/adwaita-qt/releases/tag/1.0.90

**Closed by grulja** 2019-07-02 11:38 UTC
