### ISSUE TITLE
Dark styling of Qt flatpak apps is completely broken

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [FedoraQt/adwaita-qt#177] opened 2022-09-12 15:36 UTC
With current version of kstyle adwaita, Qt apps like akregator look completely broken when dark mode is enabled.

![grafik](https://user-images.githubusercontent.com/41188546/189695688-8b77c98b-247c-42e2-b729-20d72d3841a3.png)

I originally had opened an issue foe Kstyle Adwaita but got redirected to this project. The original bug report can be found here:

https://github.com/flathub/org.kde.KStyle.Adwaita/issues/10

The default light styling works fine.

System Information:

OS: Fedora 36
KDE Runtime: 5.15-21.08
Desktop: Gnome 42

**Comment by grulja** [comment] 2022-09-20 07:36
It looks like the dark variant is not being picked up. Where did you configure your dark theme? In GNOME Control center or gnome-tweaks?

**Comment by UmarJ** [comment] 2022-09-24 00:02
Same problem on Arch Linux (pacman, not flatpak). I am using qt5ct to configure the theme since I don't use a DE. Launching the application with `akregator -style Adwaita-Dark` doesn't work either.

I've tried other KDE Qt 5 applications as well. qBittorrent, which uses Qt 6, works though. So it's either a KDE problem or a Qt 5 problem.

**Comment by Sebastian-Hirsch** [comment] 2022-09-24 10:43
> It looks like the dark variant is not being picked up. Where did you configure your dark theme? In GNOME Control center or gnome-tweaks?

I changed it in the Gnome Control Center.

![grafik](https://user-images.githubusercontent.com/41188546/192093671-419f8f2d-6dd3-4c13-8506-fbed638eda0c.png)

**Comment by julianfairfax** [comment] 2022-09-27 04:32
I also have this issue
![image](https://user-images.githubusercontent.com/43753131/192432697-b6e567ba-39c1-469c-af14-96fb645e6317.png)

**Comment by grulja** [comment] 2022-09-27 05:58
> I also have this issue ![image](https://user-images.githubusercontent.com/43753131/192432697-b6e567ba-39c1-469c-af14-96fb645e6317.png)

This doesn't look like Adwaita theme. It's most likely Material style from QML.

**Comment by julianfairfax** [comment] 2022-09-27 17:38
That is correct. It seems that wasn't installed. However, after installing the Flatpak version, I still experience this issue with the app above (OSM Scout Server). Other apps now use the correct theme, but this issue persists.

**Comment by struq** [comment] 2022-12-01 08:09
I'm also seeing this issue on some KDE apps such as Okular, but not all of them, regardless of flatpak or not. The problem seems to be that the affected apps are always using the Breeze color scheme instead of picking up the color scheme provided by adwaita-qt. 
See:
https://invent.kde.org/frameworks/kconfigwidgets/-/merge_requests/94
https://invent.kde.org/graphics/okular/-/merge_requests/461

**Comment by grulja** [comment] 2022-12-07 11:56
Duplicate of https://github.com/FedoraQt/adwaita-qt/issues/151. 

> I'm also seeing this issue on some KDE apps such as Okular, but not all of them, regardless of flatpak or not. The problem seems to be that the affected apps are always using the Breeze color scheme instead of picking up the color scheme provided by adwaita-qt. See: https://invent.kde.org/frameworks/kconfigwidgets/-/merge_requests/94 https://invent.kde.org/graphics/okular/-/merge_requests/461

Thanks for link to the merge request, I will try to test it and backport to Fedora at least.

**Closed by grulja** 2022-12-07 11:56 UTC
