### ISSUE TITLE
Build fails in symlinked directory

### ISSUE THREAD

**Issue by rrthomas** [FedoraQt/adwaita-qt#86] opened 2017-03-08 14:33 UTC
I have my `~/Downloads` directory symlinked to `$HOME/.var/Downloads`.

When I try to build the theme from a downloaded release in `~/Downloads`, I get the error:

    [ 98%] Building CXX object style/CMakeFiles/adwaita-qt5.dir/adwaita-qt5_automoc.cpp.o
    In file included from /home/rrt/Downloads/adwaita-qt-0.98/build/style/adwaita-qt5_automoc.cpp:2:0:
    /home/rrt/Downloads/adwaita-qt-0.98/build/style/moc_adwaitaaddeventfilter.cpp:9:90: fatal error: ../../../../.local/var/Downloads/adwaita-qt-0.98/style/adwaitaaddeventfilter.h: No such file or directory
compilation terminated.

It looks like some path counting went wrong: there's one too many `..`. Not sure if the cause is obvious or within the project; once I'd realised what was going wrong, simply moving to a non-symlinked directory worked (as would have changing into the directory via its real path, I guess).

**Comment by MartinBriza** [comment] 2017-03-08 14:36
I don't think this is really an adwaita-qt related bug. If you can find an other CMake-based project which doesn't fail to compile in your Downloads folder, please let me know which one is it so I can investigate how they do it to avoid this.
If there is none such project, I'd assume this problem is a CMake one and should be reported against that project instead.

**Comment by rrthomas** [comment] 2017-03-08 14:37
Also, an enormous THANK YOU for your work! Finally got nice theming of Qt5 apps on my GNOME desktop without any (obvious!) glitches.

**Comment by rrthomas** [comment] 2017-03-08 14:37
Thanks, I will do if I remember.

**Comment by MartinBriza** [comment] 2017-03-08 14:38
I'm glad you like it. I know there are glitches, still, so if you find some, please let me know of it and I'll try my best to get it fixed. :)

**Comment by rrthomas** [comment] 2017-03-08 14:53
I just tried building `CDrummond/cantata` (since Craig sent me here in the first place!) checked out to my `~/Downloads` directory; it uses `cmake`, and had no problem.

**Comment by MartinBriza** [comment] 2017-03-08 14:56
Hmm, ok, I'll look into it. Not a highest priority but on the other hand probably there's also an easy fix. For 1.0 it should be alright.

**Comment by MartinBriza** [comment] 2017-04-05 13:40
Alrighty, so I've looked at this and the problem is actually in how cmake treats symlinks in regards to automoc. So while this seems to be mostly a CMake bug, I guess we could do something about it here, too, since cantata uses CMake and Qt too. However it doesn't seem as easy to fix as I expected.

**Comment by grulja** [comment] 2020-04-20 19:37
Closing as a cmake issue.

**Closed by grulja** 2020-04-20 19:37 UTC
Labels: wontfix
